const Menu = [
    {
      id: 1,
      image: "https://www.nestleprofessional.in/sites/default/files/2022-08/MAGGI-Noodles-Chakna-756x471.jpg",
      name: "Maggi",
      category: "breakfast",
      price: "80₹",
      description: "This is Maggi made with all-natural ingredients, served on a banana leaf. It's very delicious and flavorful.",
    },
    {
      id: 2,
      image: "https://static.toiimg.com/thumb/53110049.cms?imgsize=275493&width=800&height=800",
      name: "Aloo Paratha",
      category: "breakfast",
      price: "120₹",
      description: "A traditional Indian flatbread stuffed with spiced potatoes, served with yogurt and pickle.",
    },
    {
      id: 3,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJhpqiJ_oKjHTZjfjU4P2hq2UO2kUIZczyLQ&s",
      name: "Pav Bhaji",
      category: "lunch",
      price: "150₹",
      description: "A spicy blend of mashed vegetables in tomato gravy, served with buttered buns.",
    },
    {
      id: 4,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyX80dLhwVevXCW1HVUEjSMN5qrO28zEo5Cw&s",
      name: "Veg Biryani",
      category: "lunch",
      price: "200₹",
      description: "Aromatic basmati rice cooked with mixed vegetables and fragrant spices, served with raita.",
    },
    {
      id: 5,
      image: "https://www.cookwithmanali.com/wp-content/uploads/2019/05/Paneer-Butter-Masala-500x500.jpg",
      name: "Butter Chicken",
      category: "dinner",
      price: "300₹",
      description: "Tender chicken cooked in a creamy tomato sauce with butter and spices, served with naan.",
    },
    {
      id: 6,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiU9NrykehBPxRS1QS-Q-cx0gMP7lcLTzHDw&s",
      name: "Dosa",
      category: "breakfast",
      price: "100₹",
      description: "A crispy and thin South Indian pancake made from fermented rice batter, served with sambar and chutney.",
    },
    {
      id: 7,
      image: "https://www.cookwithmanali.com/wp-content/uploads/2019/05/Paneer-Butter-Masala-500x500.jpg",
      name: "Chole Bhature",
      category: "lunch",
      price: "180₹",
      description: "A spicy chickpea curry served with deep-fried puffed bread. A classic North Indian dish.",
    },
    {
      id: 8,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCupifSPwkUDVwYEWeoGTaKiQYyCxy3PTQIg&s",
      name: "Rajma Chawal",
      category: "lunch",
      price: "150₹",
      description: "A comforting dish made of red kidney beans cooked in a thick tomato-based gravy, served with rice.",
    },
    {
      id: 9,
      image: "https://www.cookwithmanali.com/wp-content/uploads/2019/05/Paneer-Butter-Masala-500x500.jpg",
      name: "Paneer Butter Masala",
      category: "dinner",
      price: "250₹",
      description: "Paneer cubes cooked in a rich and creamy tomato gravy with butter and mild spices.",
    },
    {
      id: 10,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiU9NrykehBPxRS1QS-Q-cx0gMP7lcLTzHDw&s",
      name: "Idli Sambar",
      category: "breakfast",
      price: "80₹",
      description: "Steamed rice cakes served with a flavorful lentil-based vegetable stew called sambar.",
    },
    {
      id: 11,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7DVg6gdRsNdrupgPV5GdwTCCl61VxAkxLkA&s",
      name: "Aloo Palak",
      category: "lunch",
      price: "130₹",
      description: "A light and healthy dish made with spinach and potatoes cooked with Indian spices.",
    },
    {
      id: 12,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiU9NrykehBPxRS1QS-Q-cx0gMP7lcLTzHDw&s",
      name: "Masala Dosa",
      category: "breakfast",
      price: "120₹",
      description: "A crispy dosa stuffed with spiced mashed potatoes, served with coconut chutney and sambar.",
    },
    {
      id: 13,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7DVg6gdRsNdrupgPV5GdwTCCl61VxAkxLkA&s",
      name: "Palak Paneer",
      category: "dinner",
      price: "240₹",
      description: "Paneer cubes cooked in a smooth and mildly spiced spinach-based gravy.",
    },
    {
      id: 14,
      image: "https://www.cookwithmanali.com/wp-content/uploads/2019/05/Paneer-Butter-Masala-500x500.jpg",
      name: "Fish Curry",
      category: "dinner",
      price: "300₹",
      description: "A spicy and tangy curry made with fresh fish, cooked in coconut milk and spices.",
    },
    {
      id: 15,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYPu5hWitlUFkOngjzaOS_S25TwKtNR2mESw&s",
      name: "Paneer Roll",
      category: "lunch",
      price: "120₹",
      description: "A delicious wrap filled with marinated paneer, vegetables, and sauces.",
    },
    {
      id: 16,
      image: "https://www.cookwithmanali.com/wp-content/uploads/2019/05/Paneer-Butter-Masala-500x500.jpg",
      name: "Dal Tadka",
      category: "dinner",
      price: "160₹",
      description: "Yellow lentils cooked with aromatic tempering of spices, served with rice or roti.",
    },{
      id: 17,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyX80dLhwVevXCW1HVUEjSMN5qrO28zEo5Cw&s",
      name: "Biryani",
      category: "dinner",
      price: "180₹",
      description: "Aromatic basmati rice cooked with mixed vegetables and fragrant spices, served with raita.",
    }, 
  ];

  export default Menu;
  